#!/bin/sh

# 2014 Jon Suderman
# https://github.com/suderman/install/

# Open a terminal and run this command:
# curl https://raw.github.com/suderman/install/master/dotfiles | sh

# dotfiles directory
DOTFILES=$HOME/.dotfiles

# Check for and install dotfiles
if [ ! -d $DOTFILES ]; then

  # Ensure git exists
  curl -sS https://raw.github.com/suderman/install/master/git | sh

  # Install dotfiles
  echo "Installing $DOTFILES"
  git clone https://github.com/suderman/dotfiles.git $DOTFILES

  # Update remote url for easy updating
  cd $DOTFILES && git remote set-url origin git@github.com:suderman/dotfiles.git

fi

