#!/bin/sh

# 2014 Jon Suderman
# https://github.com/suderman/install/

# Open a terminal and run this command:
# curl https://raw.github.com/suderman/install/master/homebrew | sh

# Is this OS X or Ubuntu? 
case "`uname`" in
  
  # OS X 
  Darwin ) command -v brew >/dev/null 2>&1 || {
    echo "Installing homebrew on OS X"

    # Ensure command line tools have been installed
    curl -sS https://raw.github.com/suderman/install/master/osx-gcc | sh

    # Run install script
    ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
  }
  ;;

  # Ubuntu
  Linux ) command -v brew >/dev/null 2>&1 || {
    echo "Installing homebrew on Linux"

    # Dependencies
    sudo apt-get install build-essential curl git-core ruby libbz2-dev libcurl4-openssl-dev libexpat-dev libncurses-dev zlib1g-dev

    # Clone repo
    git clone https://github.com/Homebrew/linuxbrew.git ~/.linuxbrew
  }
  ;;
esac

