#!/bin/sh

# 2014 Jon Suderman
# https://github.com/suderman/install/

# Open a terminal and run this command:
# curl https://raw.github.com/suderman/install/master/homebrew | sh

# Check if homebrew exists
command -v brew >/dev/null 2>&1 || {

  # brew not found; 
  case "`uname`" in

    # Install homebrew on OS X 
    Darwin ) echo "Installing homebrew on OS X"

      # Ensure command line tools have been installed
      curl -sS https://raw.github.com/suderman/install/master/osx-gcc | sh

      # Run install script
      ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
      ;;

    Linux ) echo "Homebrew is only available for OS X"
      ;;

  esac
}

