#!/bin/sh

# 2014 Jon Suderman
# https://github.com/suderman/install/

# Open a terminal and run this command:
# curl https://raw.github.com/suderman/install/master/ncurses | sh

# prefix directory
PREFIX=$HOME/local

# Check for ncurses
if [ ! -d $PREFIX/include/ncurses ]; then
  
  # ncurses not found; 
  case $OSTYPE in

    # Install ncurses on OS X 
    darwin* ) echo "Not be installed on OS X"
      break;;

    # Install ncurses to ~/local
    linux* ) echo "Installing ncurses on Ubuntu"

      # Make tmp directory and change into it
      mkdir -p /tmp/ncurses && cd /tmp/ncurses

      # Download the source
      curl -sS ftp://ftp.gnu.org/gnu/ncurses/ncurses-5.9.tar.gz > /tmp/ncurses.tar.gz

      # Extract the contents into our tmp directory
      tar -xv --file=/tmp/ncurses.tar.gz --strip-components=1 --directory=/tmp/ncurses
      
      # Configure ncurses and build it
      ./configure --prefix=$PREFIX --with-default-terminfo-dir=/usr/share/terminfo --with-terminfo-dirs="/etc/terminfo:/lib/terminfo:/usr/share/terminfo"
      make && make install
      break;;

  esac
fi

