#!/bin/sh

# 2014 Jon Suderman
# https://github.com/suderman/install/

# Open a terminal and run this command:
# curl https://raw.github.com/suderman/install/master/oh-my-zsh | sh

# Check for and install oh-my-zsh
if [ ! -d $HOME/.oh-my-zsh ]; then

  # Ensure git exists
  curl -sS https://raw.github.com/suderman/install/master/git | sh

  # Clone oh-my-zsh into the home directory
  echo "Installing ~/.oh-my-zsh"
  git clone https://github.com/robbyrussell/oh-my-zsh.git $HOME/.oh-my-zsh

fi

