#!/bin/sh

# 2014 Jon Suderman
# https://github.com/suderman/install/

# Open a terminal and run this command:
# curl https://raw.github.com/suderman/install/master/rcm | sh

# dotfiles and prefix directory
DOTFILES=$HOME/.dotfiles
  
command -v rcup >/dev/null 2>&1 || {
  echo "Installing rcm"

  # Ensure homebrew has been installed
  curl -sS https://raw.github.com/suderman/install/master/homebrew | sh

  # Install with homebrew
  brew tap thoughtbot/formulae
  brew install rcm
}


# Ensure the .rcrc file exists before rcup is run at all
ln -sf $DOTFILES/rcrc $HOME/.rcrc

