#!/bin/sh

# 2014 Jon Suderman
# https://github.com/suderman/install/

# Open a terminal and run this command:
# curl https://raw.github.com/suderman/install/master/secret-dotfiles | sh

# dotfiles directory
DOTFILES=$HOME/.secret-dotfiles

# Check for and install dotfiles
if [ ! -d $DOTFILES ]; then

  # Ensure git exists
  curl -sS https://raw.github.com/suderman/install/master/git | sh

  echo "Installing $DOTFILES"
  git clone https://suderman@github.com/suderman/secret-dotfiles.git $DOTFILES

  # Check if secret dotfiles are now there
  if [ -d $DOTFILES ]; then

    # Update remote url for easy updating
    cd $DOTFILES && git remote set-url origin git@github.com:suderman/secret-dotfiles.git

    # SSH complains if these files have the wrong permissions
    chmod go-rw $DOTFILES/ssh/*

  fi
fi

