#!/bin/sh

# 2014 Jon Suderman
# https://github.com/suderman/install/

# Open a terminal and run this command:
# curl https://raw.github.com/suderman/install/master/tmuxifier | sh

# tmuxifier directory
TMX="$HOME/.tmuxifier"

# Check if the directory exists
if [ -d $TMX ]; then

  # Now check if it's a git repo
  if [ -d $TMX/.git ]; then

    # It is? Great, let update it!
    echo "Updating tmuxifier..."
    cd $TMX && git pull

  # It's not? Rename it so we can install this one
  else
    echo "Backing up existing $TMX to make room for the new one!"
    mv $TMX $TMX.backup
  fi
fi

# Check for and install tmuxifier
if [ ! -d $TMX ]; then

  # Ensure git exists
  curl -sS https://raw.github.com/suderman/install/master/git | sh

  # Clone tmuxifier into the home directory
  echo "Installing tmuxifier..."
  git clone https://github.com/jimeh/tmuxifier.git $TMX

  # Don't forget to add path
  echo "Make sure $TMX is in your path!"
  # export PATH="$HOME/.tmuxifier/bin:$PATH"

fi

